
tasks:
  - name: aws-cli
    env: 
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.0.30.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      rm awscliv2.zip
      rm -r -d aws
vscode:
  extensions:
    - 42Crunch.vscode-openapi